language: node_js
matrix:
  include:
  - os: linux
    services: docker
    language: generic
  - os: osx
    osx_image: xcode9.0
    node_js: '8'
    sudo: required
    env:
    - HOMEBREW_CASK_OPTS='--appdir=/Applications'
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine*
cache:
  yarn: true
  directories:
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update > /dev/null
    brew cask install google-chrome
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
install:
- yarn
before_script:
- git lfs pull
script:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    docker run --rm \
      --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine-chrome \
      /bin/bash -c "xvfb :99 -ac &" \
      /bin/bash -c "export DISPLAY=:99.0" \
      /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn test && yarn build -wl -p onTagOrDraft"
  else
    yarn build -m -p onTagOrDraft
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  matrix:
  - secure: i5npNbgB7XWw31iY49TK941VT72DzLdFF3i7zJQFgX7hXmUQUD0GEefcjyGfWF0yglX03v96ygdcTtMcnGTOnm7UTX13g3ziAo3wd1lOqm0aMZlvpOWnTxGVoy5B9A+luVXhUkm1ZdxDSGaOnOJ0vYj7Jc5bldInbOiKkDcpBixf0T2zS5Gm+Zp2IQbh21O0/mSxy1prKlOVwqESIBtYPBrS+264mC39CDb+o/AJwig3+6LOB8NuUkfvHnK1pT4gzxXr3DefhCb+i5MvWqdsqiolvYbohU0uNp7+6R9lDOsyHM+DzBHGvm+0KvVzzyTCy6kR6bRsRWkPBDkiFO9eDg4adpV7kN3iy+0aZoYGjidCyx1Td9XSF65UIh7R8iziLNiUO3qCO1XO+SLggNLmYQ9UUO6IODDjaO1otdMJaBTCymJxg91n1/DGChmRc5d9LyQhG4M6UVI1tPczNqRgnup7AcXMe0f1m8uHJa8xvGvYwiZm/DODPIddePiUVgvIkpeIK9/aond3g1Z/a2rLGl0Mx7vNHo7biWRXaphwz9F+a1SZMxlnYhiTWsiJFehzFkJshzKBT1QeJmVRn4Ew1icHhfsNVghtuuvGbAQfqCxi8YiGCLVB+4iodCJEBN9Ee5FRCg7r9YQjwL8PJrSI9cqZ6kMnrNP0TxVOCIFC6Qs=
