language: node_js
matrix:
  include:
  - os: linux
    node_js: '8'
    sudo: required
    env: DISPLAY=':99.0'
    dist: trusty
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
  - os: osx
    osx_image: xcode9.0
    node_js: '8'
    sudo: required
    env: HOMEBREW_CASK_OPTS='--appdir=/Applications'
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update > /dev/null
    brew cask install google-chrome
  else
    sudo dpkg --add-architecture i386
    wget https://dl.winehq.org/wine-builds/Release.key
    sudo apt-key add Release.key
    sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
    sudo apt-get update
    sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib winehq-stable icnsutils graphicsmagick
  fi
install:
- yarn
before_script:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    sh -e /etc/init.d/xvfb start
  fi
script:
- yarn test
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    yarn build -wl
  else
    yarn build -m
  fi
- yarn release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: FOctMLLr2/BgZsM8IWM9ILCQYlaKAtJaj5rkG+SfZBP8vTeuNFBHoAMxo4b9KBtNJmcnAUu94kRBe41knQwoRz32ZvF9VkqTjkM0BUDiwrRdnf+BxFALmg3Tm3FsILbESxVHNFTfszcLcXqoaawsDHcUkLpjgBXoD9XRXaqs7r/cXHfItSLaAR4kgvNbI+sU/NO0CureAFhADE9OyUniwbZbZ/8iYgw9PMd5e9bpMt7I/w7AUkvZcs5UkBfDrsMs+8m955C47KffZJ6xk4+z266mBhnpzCox6tlHlCESD8nVhfOZozP3R5HOH40SpJeslB4Oeuq8gGSXp/kA47aPybyZ5td2KO7jx+lE9X0gqFd0K8DBB2eglMRZpZL6dKFi52imM5JU5XHXLIDNyFovZ7427Ue/iUiZNIjyE1ym+5fOzo4lKWi7aLVqeHaKS47PNPelpSLw8vhIdop1VKNGQMwxLdvZ5FD1uJ3P9tBBNtDeH/ekqQ0hcMSqW3l5T3VUEVq+DBm15x+sQ3n62EcEj+0mCGbIX9G8Yg0GroPXqLHc4D4q+oxvEna37ceARS5peU/jst13IvSH03GRNVd0jAtrsLpUMFrchK4KJBM+GncnwzaErd5mBf3QH4Emr6u9hHuUsUqoJCDPZ/s0DMbEl32/7vzE8oR9IiRbMXJF+tg=
