dist: trusty
sudo: required
language: node_js
node_js:
- '7'
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
install:
- yarn
cache:
  yarn: true
script:
- export CHROME_BIN=chromium-browser
- xvfb-run -a yarn test:ci
